[2025-10-27 02:05:37] - 12 - root - CRITICAL - Error occurred in script: C:\Users\YASH\Desktop\DataScienceProjects\NetworkSecurity\networksecurity\utilities\exception.py at line: 24 error message: Test exception
